#!/bin/bash

# chmod a+x <this file>
# ln <this file> .git/hooks/<this file>

if [ `echo "!!" | grep -c 'junk'` -ne 0 ]; then
  echo committing junk branch.
  exit -1
fi

function okay? {
  if [ $? -ne 0 ]; then
    echo "nope."
    exit -1
  fi
}

cat <<USAGE

  Running ESLint.  Press CTRL+C to abort.

USAGE

./node_modules/.bin/eslint $(find app utils spec -name "*.js?")
okay?
